# Generated by Django 3.0.6 on 2020-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='description',
            field=models.CharField(blank=True, help_text='Describe about language.', max_length=100, null=True),
        ),
    ]
