# Generated by Django 3.0.6 on 2020-05-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200525_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='visible',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='visible'),
        ),
    ]
