# Generated by Django 3.0.6 on 2020-05-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200525_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_private',
            field=models.BooleanField(default=True, verbose_name='private'),
        ),
    ]
