# Generated by Django 3.0.6 on 2020-05-26 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_profile_image'),
        ('users', '0009_auto_20200525_0839'),
    ]

    operations = [
    ]
