# Generated by Django 3.0.6 on 2020-05-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200525_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('provider', 'provider'), ('client', 'client')], max_length=20),
        ),
    ]
