# Generated by Django 3.0.6 on 2020-05-26 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20200526_0446'),
        ('users', '0010_auto_20200525_1018'),
    ]

    operations = [
    ]
