# Generated by Django 3.0.6 on 2020-06-18 08:59

from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0014_userrolerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('files', models.FileField(blank=True, null=True, upload_to='videos/', validators=[users.models.validate_file_extension])),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
    ]
