# Generated by Django 3.0.6 on 2020-07-06 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_uservideos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrolerequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested By Client'), ('approved', 'Approved By Admin'), ('canceled', 'Canceled By Admin'), ('verified', 'Verified By Admin')], default='requested', max_length=20),
        ),
    ]
