# Generated by Django 3.0.6 on 2020-07-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20200706_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('client', 'Client'), ('localite', 'Localite'), ('provider', 'Provider'), ('language_verifier', 'Language Verifier')], max_length=20),
        ),
    ]
