# Generated by Django 3.0.6 on 2020-07-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20200713_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservideos',
            name='language',
            field=models.ManyToManyField(blank=True, null=True, to='users.Language'),
        ),
    ]
