# Generated by Django 3.0.6 on 2020-07-13 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_uservideos_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservideos',
            name='language',
        ),
        migrations.AddField(
            model_name='uservideos',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Language'),
        ),
    ]
