# Generated by Django 3.0.6 on 2020-07-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200713_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrolerequest',
            name='meeting_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
