# Generated by Django 3.0.6 on 2020-08-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_userrolerequest_meeting_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='multi_day',
            field=models.BooleanField(default=False),
        ),
    ]
