# Generated by Django 3.0.6 on 2020-08-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0021_userfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfavorite',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='localite',
        ),
        migrations.RemoveField(
            model_name='userfavorite',
            name='provider',
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userfavorite',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
