# Generated by Django 3.0.6 on 2020-08-12 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200812_0827'),
        ('users', '0021_customuser_multi_day'),
    ]

    operations = [
    ]
