# Generated by Django 3.0.6 on 2020-08-13 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_merge_20200812_1334'),
        ('users', '0023_merge_20200812_1226'),
    ]

    operations = [
    ]
