# Generated by Django 3.0.6 on 2020-08-19 17:53

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_merge_20200813_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
