# Generated by Django 3.0.6 on 2020-08-21 11:50

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_state_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
