# Generated by Django 3.0.6 on 2020-08-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customuser_last_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='name',
            field=models.CharField(choices=[('client', 'Client'), ('localite', 'Localite'), ('provider', 'Provider'), ('language_verifier', 'Language Verifier'), ('admin', 'admin')], max_length=20),
        ),
    ]
