# Generated by Django 3.0.6 on 2020-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20200825_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.ManyToManyField(blank=True, to='users.Language'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profession',
            field=models.ManyToManyField(blank=True, to='users.Profession'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_role',
            field=models.ManyToManyField(blank=True, to='users.UserRole'),
        ),
    ]
