# Generated by Django 3.0.6 on 2020-09-04 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_providersubscription_providersubscriptionpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersubscription',
            name='subscription_counts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='providersubscriptionpurchase',
            name='subscription_counts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
