# Generated by Django 3.0.6 on 2020-09-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200904_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providersubscriptionpurchase',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
