# Generated by Django 3.0.6 on 2020-09-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200903_1701'),
        ('users', '0030_auto_20200905_0912'),
    ]

    operations = [
    ]
