# Generated by Django 3.0.6 on 2020-07-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200713_0831'),
        ('rooms', '0002_auto_20200529_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_for', to='users.UserRole'),
        ),
    ]
