# Generated by Django 3.0.6 on 2020-09-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_created_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='chat_data/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
