# Generated by Django 3.0.6 on 2020-08-31 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_providerappointment_payment_method'),
        ('invoices', '0002_invoice_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.ProviderAppointment'),
        ),
    ]
