# Generated by Django 3.0.6 on 2020-09-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_monthlyproviderappointmentcount_monthlysubscriptioninvoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlysubscriptioninvoice',
            old_name='payee',
            new_name='provider',
        ),
    ]
