# Generated by Django 3.0.6 on 2020-09-18 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_auto_20200918_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyproviderappointmentcount',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_count', to='invoices.MonthlySubscriptionInvoice'),
        ),
    ]
