# Generated by Django 3.0.6 on 2020-09-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20200918_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlysubscriptioninvoice',
            name='current_month',
            field=models.BooleanField(default=True),
        ),
    ]
