# Generated by Django 3.0.6 on 2020-06-26 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='bank_account', max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=25)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_holder_type', models.CharField(choices=[('individual', 'Individual Type'), ('company', 'Company Type')], default='individual', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
