# Generated by Django 3.0.6 on 2020-07-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='country',
            field=models.CharField(choices=[('USA', 'US - United Stats (USA)'), ('USA', 'IND - India (IND)')], default='USA', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - United Stats (USA)'), ('USD', 'INR - India (IND)')], default='USD', max_length=50),
        ),
    ]
