# Generated by Django 3.0.6 on 2020-07-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200708_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='routing_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
