# Generated by Django 3.0.6 on 2020-07-08 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_paymentaccount_routing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
