# Generated by Django 3.0.6 on 2020-07-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_paymentaccount_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='country',
            field=models.CharField(choices=[('US', 'US - United Stats (USA)'), ('US', 'IND - India (IND)')], default='US', max_length=50),
        ),
    ]
