# Generated by Django 3.0.6 on 2020-07-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20200708_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentaccount',
            name='account_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='account_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
