# Generated by Django 3.0.6 on 2020-09-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20200708_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('Professional', models.CharField(choices=[('localite', 'For Localite'), ('provider', 'For Provider')], max_length=10)),
            ],
        ),
    ]
