# Generated by Django 3.0.6 on 2020-09-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_stripekeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='Professional',
            field=models.CharField(choices=[('localite', 'For Localite'), ('provider', 'For Provider'), ('provider_monthly', 'For Provider Monthly Subscription')], max_length=20),
        ),
    ]
