# Generated by Django 3.0.6 on 2020-09-17 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0017_auto_20200904_0612'),
        ('payment', '0009_auto_20200917_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProviderAppointmentCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.ProviderAppointment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_count', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('provider', 'appointment')},
            },
        ),
    ]
