# Generated by Django 3.0.6 on 2020-09-18 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_monthlyproviderappointmentcount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyProviderAppointmentCount',
        ),
    ]
