# Generated by Django 3.0.6 on 2020-09-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_delete_monthlyproviderappointmentcount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commission',
            unique_together={('Professional', 'is_active')},
        ),
    ]
