# Generated by Django 3.0.6 on 2020-09-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_auto_20200922_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripekeys',
            name='cancel_url',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stripekeys',
            name='success_url',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
