# Generated by Django 3.1 on 2020-09-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_profile', '0002_auto_20200629_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_account', models.CharField(max_length=256)),
                ('instagram_auth_url', models.CharField(max_length=256)),
                ('instagram_access_token_url', models.CharField(max_length=256)),
                ('instagram_app_id', models.CharField(max_length=256)),
                ('instagram_app_secret', models.CharField(max_length=256)),
                ('instagram_redirect_url', models.CharField(max_length=256)),
                ('instagram_media_url', models.CharField(max_length=256)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
