# Generated by Django 3.0.6 on 2020-06-13 06:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('blogpost', '0002_bruckeindexpage_bruckepage_bruckerelatedposts_comingsoonindexpage_comingsoonpage_comingsoonpagegalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('name', models.CharField(blank=True, help_text='categories your blog . ', max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date_posted', models.DateField(auto_now=True)),
                ('content', wagtail.core.fields.RichTextField(blank=True, help_text='describe your blog our here ! ')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
