# Generated by Django 3.0.6 on 2020-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_auto_20200613_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bruckepage',
            name='introduction',
            field=models.TextField(blank=True, help_text='About Your blog', null=True),
        ),
    ]
