# Generated by Django 3.0.6 on 2020-07-02 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_uservideos'),
        ('blogpost', '0004_auto_20200627_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruckepage',
            name='state',
            field=models.ForeignKey(blank=True, help_text='select the city name instate of state ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.State'),
        ),
    ]
