# Generated by Django 3.0.6 on 2020-07-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_bruckepage_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruckepage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
