# Generated by Django 3.0.6 on 2020-07-02 13:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0006_bruckepage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruckepage',
            name='bruke_content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='describe the thing that we are allow to do '),
        ),
    ]
