# Generated by Django 3.0.6 on 2020-09-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0008_remove_bruckepage_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='bruckepage',
            name='introduction',
            field=models.CharField(help_text='shot description about the page', max_length=50, null=True),
        ),
    ]
