# Generated by Django 3.0.6 on 2020-09-03 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_choice_1',
            field=models.CharField(blank=True, choices=[('on_time', 'on time at location'), ('late', 'late at locations')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_choice_2',
            field=models.CharField(blank=True, choices=[('communicates_well', 'communicate welll'), ('needs_to_be_clearer', 'need to be clear')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='review_choice_3',
            field=models.CharField(blank=True, choices=[('easy_to_work_with', 'easy to work'), ('challenging_to_work_with', 'challanging to work with')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL),
        ),
    ]
