# Generated by Django 3.0.6 on 2020-09-05 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reportaproblem'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportaproblem',
            name='reason',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Report Reason'),
        ),
    ]
