# Generated by Django 3.0.6 on 2020-05-14 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_date_1', models.DateField(blank=True, null=True)),
                ('requested_date_1_timeslots', models.TextField(blank=True, null=True)),
                ('requested_date_2', models.DateTimeField(blank=True, null=True)),
                ('requested_date_2_timeslots', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Created', 'Request created (by client)'), ('reshedule_reuested', 'Reschedule Requested (by client or provider)'), ('with_provider', 'Request accepted and appointment created (by provider)'), ('with_client', 'Request accepted by client (Final stage - means both client and provider accepted appointment)'), ('compelted', 'Appointment completed (by provider)')], default='Created', max_length=20)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestee', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
