# Generated by Django 3.0.6 on 2020-06-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='requested_date_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
