# Generated by Django 3.0.6 on 2020-06-03 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_auto_20200601_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_comment', models.TextField(blank=True, null=True)),
                ('provider_comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('created', 'Created By Client'), ('approved', 'Approved By Provider'), ('canceled', 'Canceled By Provider')], default='created', max_length=20)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('requestee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider', to=settings.AUTH_USER_MODEL)),
                ('requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
