# Generated by Django 3.0.6 on 2020-06-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_providerappointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerappointment',
            name='request_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
