# Generated by Django 3.0.6 on 2020-06-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_auto_20200603_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerappointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested By Client'), ('approved', 'Approved By Provider'), ('canceled', 'Canceled By Provider'), ('completed', 'Appointment Completed')], default='requested', max_length=20),
        ),
    ]
