# Generated by Django 3.0.6 on 2020-06-05 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20200604_0500'),
        ('appointments', '0005_auto_20200604_1239'),
    ]

    operations = [
    ]
