# Generated by Django 3.0.6 on 2020-06-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_auto_20200608_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('Created', 'Request created (by client)'), ('reshedule_reuested', 'Reschedule Requested (by client or provider)'), ('with_provider', 'Request accepted and appointment created (by provider)'), ('with_client', 'Request accepted by client (Final stage - means both client and provider accepted appointment)'), ('compelted', 'Appointment completed (by provider)')], default='Created', max_length=20),
        ),
    ]
