# Generated by Django 3.0.6 on 2020-06-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_auto_20200609_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('created', 'Request created (by client)'), ('rescheduled_requested', 'Reschedule Requested (by client or provider)'), ('with_provider', 'Request accepted and appointment created (by provider)'), ('with_client', 'Request accepted by client (Final stage - means both client and provider accepted appointment)'), ('completed', 'Appointment completed (by provider)')], default='created', max_length=25),
        ),
    ]
