# Generated by Django 3.0.6 on 2020-06-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_auto_20200609_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date_1_timeslots',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date_2_timeslots',
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_date_1_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_date_1_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_date_2_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='requested_date_2_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
