# Generated by Django 3.0.6 on 2020-06-17 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20200615_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date_1',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date_1_end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date_1_start_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date_2',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date_2_end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='requested_date_2_start_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.CreateModel(
            name='BookingDates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('confirmed', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='appointments.Appointment')),
            ],
        ),
    ]
