# Generated by Django 3.0.6 on 2020-06-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_auto_20200617_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerappointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested By Customer'), ('approved', 'Approved By Provider'), ('canceled', 'Canceled By Provider'), ('completed', 'Appointment Completed')], default='requested', max_length=20),
        ),
    ]
