# Generated by Django 3.0.6 on 2020-08-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0013_auto_20200622_0442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='notes',
            new_name='customer_comment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='localite_comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
