# Generated by Django 3.0.6 on 2020-08-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_auto_20200813_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('canceled', 'Canceled'), ('created', 'Request created (by Customer)'), ('rescheduled_requested', 'Reschedule Requested (by Customer)'), ('rescheduled_accepted', 'Reschedule Accepted (by Localite)'), ('with_provider', 'Request accepted and Booking created (by Localite)'), ('with_client', 'Request accepted by Customer (Final stage - means both Customer and Localite accepted Booking)'), ('completed', 'Booking completed (by Localite)')], default='created', max_length=25),
        ),
    ]
