# Generated by Django 3.0.6 on 2020-08-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0015_auto_20200813_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerappointment',
            name='payment_method',
            field=models.CharField(choices=[('through_platform', 'Payment Through Platform'), ('other_options', 'I Have Other Options')], default='through_platform', max_length=20),
        ),
    ]
