# Generated by Django 3.0.6 on 2020-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0016_providerappointment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerappointment',
            name='payment_method',
            field=models.CharField(choices=[('through_platform', 'Payment Through Platform'), ('other_options', 'Other Payment Options')], default='through_platform', max_length=20),
        ),
    ]
